services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
db:
  image: postgres:latest
  container_name: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=mydatabase
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root